name: nsc2026
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py311h2ed03ae_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alabaster=1.0.0=pyhd8ed1ab_1
  - aom=3.6.0=hcec6c5f_0
  - applaunchservices=0.3.0=pyh534df25_4
  - appnope=0.1.4=pyhd8ed1ab_1
  - arrow=1.4.0=pyhcf101f3_0
  - arrow-cpp=19.0.0=hb704434_4
  - astroid=4.0.3=py311h6eed73b_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - asyncssh=2.21.1=pyhd8ed1ab_0
  - atomicwrites=1.4.1=pyhd8ed1ab_1
  - attrs=25.4.0=pyhcf101f3_1
  - autopep8=2.0.4=pyhd8ed1ab_0
  - aws-c-auth=0.9.0=h46256e1_1
  - aws-c-cal=0.9.2=h46256e1_0
  - aws-c-common=0.12.3=h46256e1_0
  - aws-c-compression=0.3.1=h46256e1_1
  - aws-c-event-stream=0.5.5=h46256e1_0
  - aws-c-http=0.10.2=h46256e1_0
  - aws-c-io=0.20.1=h46256e1_0
  - aws-c-mqtt=0.13.2=he61ece7_0
  - aws-c-s3=0.8.3=h46256e1_0
  - aws-c-sdkutils=0.2.4=h46256e1_0
  - aws-checksums=0.2.7=h46256e1_0
  - aws-crt-cpp=0.32.10=h6d0c2b6_0
  - aws-sdk-cpp=1.11.528=he026a02_1
  - babel=2.17.0=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.2.0=pyhcf101f3_2
  - bcrypt=5.0.0=py311hd2a4513_1
  - beautifulsoup4=4.14.3=pyha770c72_0
  - binaryornot=0.4.4=pyhd8ed1ab_2
  - black=26.1.0=pyh866005b_0
  - blas=1.0=openblas
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - bokeh=3.6.2=py311hecd8cb5_0
  - boost-cpp=1.82.0=ha357a0b_2
  - bottleneck=1.4.2=py311h9b7fc35_0
  - brotli-python=1.0.9=py311h6d0c2b6_9
  - brotlicffi=1.0.9.2=py311h6d0c2b6_1
  - bzip2=1.0.8=h6c40b1e_6
  - c-ares=1.19.1=h6c40b1e_0
  - ca-certificates=2025.7.15=hecd8cb5_0
  - cairo=1.16.0=h08824b9_6
  - cattrs=25.3.0=pyhd8ed1ab_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=1.17.1=py311h9205ec4_1
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.2.1=py311hecd8cb5_0
  - cloudpickle=3.1.1=py311hecd8cb5_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.1=py311h1962661_0
  - cookiecutter=2.6.0=pyhd8ed1ab_1
  - cryptography=45.0.5=py311hc0e11ad_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.27=h1e973b7_6
  - cytoolz=1.1.0=py311hf197a57_1
  - dask=2023.12.1=pyhd8ed1ab_0
  - dav1d=1.2.1=h6c40b1e_0
  - debugpy=1.8.20=py311hc63dfec_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.3.1=pyhd8ed1ab_1
  - diff-match-patch=20241021=pyhd8ed1ab_1
  - dill=0.4.1=pyhcf101f3_0
  - docstring-to-markdown=0.17=pyhe01879c_0
  - docutils=0.22.4=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6d0c2b6_0
  - flake8=7.1.2=pyhd8ed1ab_0
  - fontconfig=2.14.1=h269ac6a_3
  - fonttools=4.55.3=py311h46256e1_0
  - freetype=2.13.3=h02243ff_0
  - fribidi=1.0.10=haf1e3a3_0
  - frozenlist=1.7.0=py311h7a2b322_0
  - fsspec=2025.7.0=py311he13d532_0
  - fzf=0.67.0=h1ecb644_0
  - gettext=0.21.0=h4e8c18a_2
  - gflags=2.2.2=hcec6c5f_1
  - glib=2.84.2=h918fcf5_0
  - glib-tools=2.84.2=h918fcf5_0
  - glog=0.5.0=hcec6c5f_1
  - graphite2=1.3.14=he9d5cce_1
  - gst-plugins-base=1.14.5=hb4a159a_2
  - gstreamer=1.14.5=h06b91d7_2
  - harfbuzz=10.2.0=h060d35a_1
  - heapdict=1.0.1=pyhd3eb1b0_0
  - icu=73.1=hcec6c5f_0
  - idna=3.11=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=py311hecd8cb5_0
  - importlib_metadata=8.5.0=hd8ed1ab_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - inflection=0.5.1=pyhd8ed1ab_1
  - iniconfig=2.1.0=py311hecd8cb5_0
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipykernel=6.31.0=pyh5552912_0
  - ipython=9.10.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isort=7.0.0=pyhd8ed1ab_0
  - jaraco.classes=3.4.0=pyhcf101f3_3
  - jaraco.context=6.1.0=pyhcf101f3_0
  - jaraco.functools=4.4.0=pyhcf101f3_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jellyfish=1.2.1=py311hef35832_1
  - jinja2=3.1.6=py311hecd8cb5_0
  - jpeg=9e=h46256e1_3
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - keyring=25.7.0=pyh534df25_0
  - kiwisolver=1.4.8=py311h6d0c2b6_0
  - krb5=1.20.1=h049b76e_0
  - lcms2=2.16=h31d93a5_1
  - lerc=4.0.0=h6d0c2b6_0
  - libabseil=20250127.0=cxx17_h548131f_0
  - libavif=1.1.1=h46256e1_0
  - libboost=1.82.0=hf53b9f2_2
  - libbrotlicommon=1.0.9=h46256e1_9
  - libbrotlidec=1.0.9=h46256e1_9
  - libbrotlienc=1.0.9=h46256e1_9
  - libclang=14.0.6=default_hdb78580_1
  - libclang13=14.0.6=default_h953c2e9_1
  - libcurl=8.14.1=h1448931_1
  - libcxx=19.1.7=haebbb44_3
  - libdeflate=1.22=h46256e1_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h9ed2024_1
  - libevent=2.1.12=h04015c4_1
  - libffi=3.4.4=hecd8cb5_1
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libglib=2.84.2=heb90364_0
  - libgrpc=1.71.0=hf2926fd_0
  - libiconv=1.16=h6c40b1e_3
  - libkrb5=1.21.3=h54be378_4
  - libllvm14=14.0.6=h26321d7_4
  - libnghttp2=1.57.0=h9beae6a_0
  - libntlm=1.8=h6e16a3a_0
  - libopenblas=0.3.29=h3f8574a_0
  - libpng=1.6.39=h6c40b1e_0
  - libpq=17.4=h40f65ae_2
  - libprotobuf=5.29.3=h66a43dd_1
  - libre2-11=2024.07.02=hab2016f_0
  - libsodium=1.0.18=hbcb3906_1
  - libspatialindex=2.1.0=h501a4e1_0
  - libssh2=1.11.1=h3a17b82_0
  - libthrift=0.15.0=h70b4b81_2
  - libtiff=4.7.0=h2dfa3ea_0
  - libwebp-base=1.3.2=h46256e1_1
  - libxml2=2.13.8=h6070cd6_0
  - llvm-openmp=19.1.7=h5048363_2
  - llvmlite=0.44.0=py311hfa5e528_1
  - lmdb=0.9.35=hc5a0132_0
  - locket=1.0.0=py311hecd8cb5_0
  - lsprotocol=2025.0.0=pyhe01879c_0
  - lz4=4.3.2=py311h46256e1_1
  - lz4-c=1.9.4=hcec6c5f_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.2=py311h46256e1_0
  - matplotlib=3.10.0=py311hecd8cb5_0
  - matplotlib-base=3.10.0=py311h919b35b_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.2.0=pyhcf101f3_0
  - more-itertools=10.8.0=pyhcf101f3_1
  - msgpack-python=1.1.1=py311h6d0c2b6_0
  - multidict=6.7.0=py311h24ee9f8_0
  - mypy_extensions=1.1.0=pyha770c72_0
  - mysql=8.4.0=h5364baf_2
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert=7.17.0=h14065e2_0
  - nbconvert-core=7.17.0=pyhcf101f3_0
  - nbconvert-pandoc=7.17.0=hc3985f0_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h923df54_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numba=0.61.2=py311h2d33a94_0
  - numexpr=2.11.0=py311h20bc273_0
  - numpy=1.26.4=py311h91b6869_0
  - numpy-base=1.26.4=py311hb3ec012_0
  - numpydoc=1.10.0=pyhcf101f3_0
  - openjpeg=2.5.2=h2d09ccc_1
  - openldap=2.6.4=hd88b477_0
  - openssl=3.0.17=hee2dfae_0
  - orc=2.1.1=h4dda5a6_0
  - packaging=25.0=py311hecd8cb5_0
  - pandas=2.3.1=py311hebe84f7_0
  - pandoc=3.9=h694c41f_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=py311hecd8cb5_0
  - pathspec=1.0.4=pyhd8ed1ab_0
  - pcre2=10.42=h9b97e30_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py311h25d8182_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=hb254d66_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - pluggy=1.5.0=py311hecd8cb5_0
  - ply=3.11=pyhd8ed1ab_3
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py311ha3cf9ac_0
  - psutil=5.9.0=py311h46256e1_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=19.0.0=py311h6d0c2b6_1
  - pyarrow-hotfix=0.7=pyhd8ed1ab_0
  - pycodestyle=2.12.1=pyhd8ed1ab_1
  - pyconify=0.2.1=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydocstyle=6.3.0=pyhd8ed1ab_1
  - pyflakes=3.2.0=pyhd8ed1ab_1
  - pygithub=2.8.1=pyhd8ed1ab_0
  - pygments=2.19.1=py311hecd8cb5_0
  - pyjwt=2.11.0=pyhd8ed1ab_0
  - pylint=4.0.4=pyhcf101f3_0
  - pylint-venv=3.0.4=pyhd8ed1ab_1
  - pyls-spyder=0.4.0=pyhd8ed1ab_1
  - pynacl=1.5.0=py311h2725bcf_3
  - pyobjc-core=11.0=py311hfbc4093_0
  - pyobjc-framework-cocoa=11.0=py311hfbc4093_0
  - pyobjc-framework-coreservices=11.0=py311h4d7f069_0
  - pyobjc-framework-fsevents=11.0=py311h6eed73b_0
  - pyopenssl=25.1.0=pyhd8ed1ab_0
  - pyparsing=3.2.0=py311hecd8cb5_0
  - pyqt=5.15.10=py311h6d0c2b6_1
  - pyqt5-sip=12.13.0=py311h46256e1_1
  - pyqtwebengine=5.15.10=py311h6d0c2b6_1
  - pysocks=1.7.1=py311hecd8cb5_0
  - pytest=8.4.1=py311hecd8cb5_0
  - python=3.11.13=hbff2529_0
  - python-dateutil=2.9.0post0=py311hecd8cb5_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gssapi=1.8.2=py311h0395c84_2
  - python-lmdb=1.6.2=py311h6d0c2b6_0
  - python-lsp-black=2.0.0=pyhff2d567_1
  - python-lsp-jsonrpc=1.1.2=pyhff2d567_1
  - python-lsp-ruff=2.3.0=pyhcf101f3_0
  - python-lsp-server=1.14.0=pyh332efcf_0
  - python-lsp-server-base=1.14.0=pyhd8ed1ab_0
  - python-slugify=8.0.4=pyhd8ed1ab_1
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - python.app=1.4=py311h13e5629_5
  - python_abi=3.11=2_cp311
  - pytokens=0.4.1=py311ha332486_0
  - pytoolconfig=1.2.5=pyhd8ed1ab_1
  - pytz=2025.2=py311hecd8cb5_0
  - pyuca=1.2=pyhd8ed1ab_2
  - pyxdg=0.28=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h46256e1_0
  - pyzmq=27.1.0=py311h0ab6910_0
  - qdarkstyle=3.2.3=pyhd8ed1ab_1
  - qstylizer=0.2.4=pyhff2d567_0
  - qt-main=5.15.2=hf83fbd5_12
  - qt-webengine=5.15.9=h90a370e_7
  - qtawesome=1.4.1=pyh9208f05_0
  - qtconsole=5.7.0=pyhd8ed1ab_0
  - qtconsole-base=5.7.0=pyha770c72_0
  - qtpy=2.4.3=pyhd8ed1ab_1
  - re2=2024.07.02=h1962661_0
  - readline=8.3=h49f2429_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - rich=14.3.2=pyhcf101f3_0
  - roman-numerals=4.1.0=pyhd8ed1ab_0
  - rope=1.14.0=pyhd8ed1ab_0
  - rpds-py=0.30.0=py311hd2a4513_0
  - rtree=1.4.1=pyh11ca60a_0
  - ruff=0.15.0=h5930b28_0
  - scipy=1.16.0=py311hcd1e4c7_0
  - setuptools=78.1.1=py311hecd8cb5_0
  - sip=6.7.12=py311hd39e593_0
  - six=1.17.0=py311hecd8cb5_0
  - snappy=1.2.1=h6d0c2b6_0
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.8.3=pyhd8ed1ab_0
  - sphinx=9.0.4=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - spyder=6.1.2=hd8ed1ab_0
  - spyder-base=6.1.2=osx_pyh1a5313d_0
  - spyder-kernels=3.1.2=unix_pyh707e725_0
  - sqlite=3.50.2=hc8b0dd6_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - superqt=0.7.8=pyh9208f05_0
  - tbb=2021.8.0=ha357a0b_0
  - tblib=3.1.0=py311hecd8cb5_0
  - text-unidecode=1.3=pyhd8ed1ab_2
  - textdistance=4.6.3=pyhd8ed1ab_1
  - three-merge=0.1.1=pyhd8ed1ab_1
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.15=h3a5a201_0
  - tomli=2.4.0=pyhcf101f3_0
  - tomlkit=0.14.0=pyha770c72_0
  - toolz=1.0.0=py311hecd8cb5_0
  - tornado=6.5.1=py311h46256e1_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=he532380_0
  - ujson=5.11.0=py311hc651eee_1
  - unicodedata2=15.1.0=py311h46256e1_1
  - urllib3=2.5.0=py311hecd8cb5_0
  - utf8proc=2.6.1=h6c40b1e_1
  - watchdog=6.0.0=py311hf197a57_2
  - wcwidth=0.5.3=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - whatthepatch=1.0.7=pyhd8ed1ab_1
  - wheel=0.45.1=py311hecd8cb5_0
  - wrapt=2.1.1=py311hc71d4c3_0
  - wurlitzer=3.1.1=pyhd8ed1ab_1
  - xyzservices=2022.9.0=py311hecd8cb5_1
  - xz=5.6.4=h46256e1_1
  - yaml=0.2.5=haf1e3a3_0
  - yapf=0.43.0=pyhd8ed1ab_1
  - yarl=1.22.0=py311he13f9b5_0
  - zeromq=4.3.5=h93d8f39_0
  - zict=3.0.0=py311hecd8cb5_0
  - zipp=3.21.0=py311hecd8cb5_0
  - zlib=1.2.13=h4b97444_1
  - zstd=1.5.6=h138b38a_0
prefix: /Users/mikkel/miniforge3/envs/nsc2026
